# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robot_control.Robot'),
        ),
    ]
