# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0002_auto_20160519_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='control_robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='robot_control.Robot'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='robot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robot_control.Robot'),
            preserve_default=False,
        ),
    ]
