# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0004_auto_20160519_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
