# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_control', '0008_auto_20160519_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='vote',
            field=models.CharField(choices=[('U', 'up'), ('D', 'down'), ('L', 'left'), ('R', 'right'), ('S', 'stop')], max_length=1),
        ),
    ]
